name: CI
on:
  pull_request:
    branches: [develop, master]
  push:
    branches: [develop, master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run format
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage #name of the folder
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload build folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build #name of the folder
      - name: ZIP Assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # It means that a release will be created only when there is a PUSH to Master        
        run: |
          zip -r build.zip ./build
          zip -r coverage.zip ./coverage
      - name: Create a Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # It means that a release will be created only when there is a PUSH to Master
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_TOKEN }} #This tocken contains the repo control
      - run: npm install -g surge
      - name: Deploy to staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop' # Only will be deployed in the staging environment
        run: npx surge --project ./build -- domain http://remarkable-blood.surge.sh
      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Only will be deployed in the production environment
        run: npx surge --project ./build -- domain http://repulsive-home.surge.sh
      - name: Upload Coverage Reports
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' # Only will be get the coverage report in production environment
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}